### ISSUE TITLE
Standardize ID encoding and create reference ID generators

### ISSUE THREAD

**Issue by kpwebb** [sharedstreets/sharedstreets-ref-system#8]
We need to standardize-base encoding for IDs and create reference ID generation example code as part of spec.

*Encoding*
Currently we're using base58 (semi-random choice) but realized that there's insufficient library support to make new implementations easy to build and test. Should we fall back to base16 despite space issue? Higher-base options seem fraught ([no clear answers about which is best](https://stackoverflow.com/questions/2827627/what-is-the-most-efficient-way-to-encode-an-arbitrary-guid-into-readable-ascii))

*reference ID generators*
let's move these to spec an document (@kpwebb)

**Comment by migurski** [comment]
You’re right that everything beyond base16 has character ambiguity issues!

I would borrow a page from Git here, and use base16 but accept that people may [use prefix matches instead of the whole thing](https://git-scm.com/book/en/v2/Git-Tools-Revision-Selection):

> Git is smart enough to figure out what commit you’re referring to if you provide the first few characters of the SHA-1 hash, as long as that partial hash is at least four characters long and unambiguous; that is, no other object in the object database can have a hash that begins with the same prefix.

My expectation is that the hashes alone will come with accompanying, redundant geo information. A hash match allows for shortcuts, but in the case of changed data (such as SharedStreets representations from different data sources, or OSM extracted at different times) you’d be lacking perfect hash matches and doing nearby searches.

**Comment by kpwebb** [comment]
Great! Seems like a simple/easy solution. Let's do base16. I'll switch @sharedstreets-builder to use these and should match your Python code. @DenisCarriere can you update the JS libs to base16?

I also like prefix matching as an idea. We can explore this while working on the API endpoint for sub-tile-level data.

**Comment by DenisCarriere** [comment]
@kpwebb @migurski Sounds like a good plan, Python & Node.js both have easy to use native libraries for encoding Base16 (hex).

👍 on the prefix matching! 🚀 

**python**
```py
import hashlib

def generateHash(message):
    return hashlib.md5(message).digest('hex')
```
**node.js**

```js
import { createHash } from 'crypto'

function generateHash (message) {
  return createHash('md5').update(message).digest('hex')
}
```

## Tests

```js
generateHash('Intersection 110.000000 45.000000') // => '71f34691f182a467137b3d37265cb3b6'
generateHash('Intersection -74.003388 40.634538') // => '103c2dbe16d28cdcdcd5e5e253eaa026'
generateHash('Intersection -74.004107 40.634060') // => '0f346cb98b5d8f0500e167cb0a390266'
```

**Comment by kpwebb** [comment]
Updated SharedsStreets Builder and the sharedstreets-ref docs to reflect switch to  hex.
